### ISSUE TITLE
Windows line endings in headers

### ISSUE THREAD

**Issue by Lastique** [klemens-morgenstern/boost-process#88]
I can see some of the headers in Boost.Process (for example, boost/process/cmd.hpp, boost/process/env.hpp) contain Windows line endings. Incorrect line endings have been released in Boost 1.64 packages for POSIX systems.

Please, convert line endings to POSIX. You can configure automatic conversion of line endings locally on Windows machines as described here: https://help.github.com/articles/dealing-with-line-endings/. Note that there is `.gitattributes` at Boost root that provides file types for most of the content in Boost, so you don't have to do it yourself.

**Comment by Lastique** [comment]
Although, now I noticed that `.gitattributes` is reproduced in every submodule, except Boost.Process. Perhaps, git does not always use `.gitattributes` from the superproject. In that case it might make sense to copy it into Boost.Process.

**Comment by klemens-morgenstern** [comment]
Thanks, I'll fix that soon. My windows actually converts that automatically, I'm not sure where they came from.

**Comment by klemens-morgenstern** [comment]
I think I fixed that now in ba14d9f870ecc1956a4c95c6f646e4fa7d9a7248, but might I be as bold as to ask you to double check that? It should be CRLF now everywhere.

**Comment by Lastique** [comment]
Um, that commit it in you fork, not boostorg.

> It should be CRLF now everywhere.

I think you meant to say LF. :)

**Comment by klemens-morgenstern** [comment]
Heh, you see why I need someone to check that? :)

Yeah looks like LF to me, I'm just confused because git might change that around.

**Comment by Lastique** [comment]
In your fork's develop branch I can still see CRLF line endings in headers and no `.gitattributes`.

I think, the best way to solve this is to apply `fromdos` to every file, commit, and then add `.gitattributes` so that new files are handled properly.

**Comment by klemens-morgenstern** [comment]
https://github.com/klemens-morgenstern/boost-process/tree/ba14d9f870ecc1956a4c95c6f646e4fa7d9a7248 

Well in the whitespace branch it should be fixed, just checked.

**Comment by Lastique** [comment]
See https://github.com/boostorg/process/pull/7.

**Comment by Lastique** [comment]
> Well in the whitespace branch it should be fixed

Oh, the whitespace branch. Yes, it looks ok to me.

**Comment by klemens-morgenstern** [comment]
Alright, merged it. Thanks for your help!

I'll push my chaned to boostorg/process when more changes are ready.
